# Motivation

> Random Matrix is one of the most mysterious objects in mathematics. It is a bridge con- necting linear algebra and probability theory, which is significant for (statistical) machine learning.

> In general, both data and the noise imposed on them are treated as random variables sampled from some (unknown) distributions. The main content of this course is about designing distributions for random variables and estimating distributions from their samples.

> Before studying the properties of random matrices, let’s start to generate some.


# Task 1

Design a function $f(M,N,a,b)$ to generate a matrix $A = [a_{mn}] \in [a,b]^{M\times N}$. Each element of the matrix is a random variable obeying a uniform distribution in the interval $[a,b]$, i.e., $a_{mn} \sim$ Uniform($[a, b]$).

## Solution 1

We can use `np.random.uniform(a,b,size=(m,n))` to generate a m $\times$ n matrix where each element follows $U[a,b]$

In [10]:
import numpy as np
def f(m: int, n: int, a: float, b: float) -> np.ndarray:
    """
    Generate a uniform random matrix
    :param m: the number of rows of the matrix
    :param n: the number of columns of the matrix
    :param a: the lower bound of the uniform distribution
    :param b: the upper bound of the uniform distribution
    :return:
        x in [a, b]^{m x n}, a random matrix
    """
    return np.random.uniform(a, b, size=(m,n))

f(4, 3, 0, 1)

array([[0.7635667 , 0.31655609, 0.91897546],
       [0.06051409, 0.65507213, 0.67280552],
       [0.4587648 , 0.93090454, 0.81637024],
       [0.14153436, 0.3921457 , 0.11930882]])

# Task 2
Design a function $g(M, N, p)$ to generate a matrix $A = [a_{mn}] \in \{0, 1\}^{M\times N}$ , $p \in [0, 1]$. Each element of the matrix is a random variable obeying a Bernoulli distribution, i.e., $a_{mn} \sim$ Bernoulli($p$), which means that the probability of $a_{mn} = 1$ is $p$ (equivalently, the probability of $a_{mn} = 0$ is $1−p$).

## Solution 2

Bernoulli distribution generation is realized by `numpy.random.choice(a, size=None, replace=True, p=None)`:
> `a`: If `a` is an integer，then we sample from integer from 0 to`a`-1. If `a` is an array, we sample from this specific array

> `size`: The size of our generated data (one number, vector or matrix)

> `replace`: Sampling w/ or w/o replacement

> `p`: The probability of each sampled element. The size of `p` should be the same as `a`

In [21]:
import numpy as np
def g(m: int, n: int, p: float) -> np.ndarray:
    """
    Generate a Bernoulli random matrix
    :param m: the number of rows of the matrix
    :param n: the number of columns of the matrix
    :param p: in [0, 1], the parameter of the Bernoulli matrix
    :return:
        x in [a, b]^{m x n}, a random matrix
    """
    return np.random.choice([0, 1], size=(m, n), p=[1-p, p])

g(4, 3, 0.5)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 1]])

# Task 3

Could you implement $g(M, N, p)$ based on $f (M, N, a, b)$? If yes, design an evaluation method to verify the correctness of your implementation.

## Solution 3

We can first generate a matrix where each element follows $U[0,1]$. If the element $<p$, then under $g(M,N,p)$, this element corresponds to 0, otherwise it corresponds to 1.

For verification, we use LLN and Moment Methods: For large $n$, MoM estimator $\hat p\overset{p}{\rightarrow}p$, so for the `mat1` and `mat2` generated by `g` and `g2`, `mat1.sum()/(m*n)` and `mat2.sum()/(m*n)` should be similar and approximately $p$.

In [38]:
def g2(m: int, n: int, p: float) -> np.ndarray:
    """
    Generate a Bernoulli random matrix (based on the function of uniform random matrix)
    :param m: the number of rows of the matrix
    :param n: the number of columns of the matrix
    :param p: in [0, 1], the parameter of the Bernoulli matrix
    :return:
        x in [a, b]^{m x n}, a random matrix
    """
    matrix = f(m, n, 0, 1)
    return (matrix < p).astype(int)
    
g2(4, 3, 0.5)

# Verification
m, n = 10000, 10000
mat1, mat2 = g(m,n,0.4), g2(m,n,0.4)

mat1.sum()/(m*n), mat2.sum()/(m*n)

(0.39991739, 0.40010684)

# Task 4

Design a function $h(M, N, a, b)$ to generate a matrix $A = [a_{mn}] \in \{0, 1\}^{M\times N}$ , where $a < 0$ and $b > 0$. The elements of the matrix obey the following rule:
$$
P (a_{mn} \sim U[a, 0]) = P (a_{mn} ∼ U[0, b]) = 0.5.
$$

## Solution 4

The condition means that each element $a_{mn}$ is either generated with $U[a,0]$ with probability 0.5 or with $U[0,b]$ with probability 0.5.

In [40]:
def h(m: int, n: int, a: float, b: float) -> np.ndarray:
    """
    Generate a random matrix
    P(x ~ Uniform[a, 0]) = P(x ~ Uniform[b, 0]) = 0.5

    :param m: the number of rows of the matrix
    :param n: the number of columns of the matrix
    :param a: the lower bound of the uniform distribution
    :param b: the upper bound of the uniform distribution
    :return:
        x in [a, b]^{m x n}, a random matrix
    """
    mat1 = f(m, n, a, 0)
    mat2 = f(m, n, 0, b)
    choice = g(m, n, 0.5)
    return np.where(choice == 0, mat1, mat2)

h(4, 3, -2, 2)


array([[-1.66341022, -0.03028017,  1.2527392 ],
       [ 1.29715263,  1.73610983,  1.98891835],
       [-0.86862337,  0.90100233,  1.96599647],
       [ 1.87401522, -0.94264801, -1.88108748]])