# O método da Eliminação de Gauss

Vamos implementar o método da Eliminação de Gauss sem qualquer preocupação com estratégia de pivoteamento. Essas estratégias serão consideradas mais adiante.

In [1]:
using LinearAlgebra

Vamos considerar buscar a solção do sistema $Ax=b$. Para isso vamos implementar a função "eliminacao" que recebe $A$ e $b$ e retorna $\tilde{A}$ e $\tilde{b}$, onde $\tilde{A}$ é uma matriz triangular superior linha equivalente a $A$ e $\tilde{b}$ é linha equivalente a $b$.  

In [2]:
function eliminacao(A,b)
    n = size(b,1); 
    for k in 1 : n-1
        for i in k+1 : n
            m = A[i,k] / A[k,k];
            A[i,k] = 0.0;
            for j in k+1 : n
                A[i,j] = A[i,j] - m * A[k,j];
            end
            b[i] = b[i] - m * b[k];
        end
    end
    return(A,b)
end

eliminacao (generic function with 1 method)

A função "solucao" recebe as matrizes $\tilde{A}$ e $\tilde{b}$ da função anterior e calcular a solução do sistema por meio de uma substituição.

In [3]:
function solucao(A,b)
    n = size(b,1);
    x = zeros(n,1); 
    x[n] = b[n] / A[n,n];
    for k in n-1 : -1 : 1
        s = 0.0;
        for j in k+1 : n
            s = s + A[k,j] * x[j];
        end
        x[k] = (b[k] - s) / A[k,k];
    end
    return(x)
end
    

solucao (generic function with 1 method)

Com as funções acima, implementamos a função "eligauss" que dirigirá todo o processo de solução.

In [4]:
function eligauss(A,b)
    (A,b) = eliminacao(A,b);
    return solucao(A,b);
end

eligauss (generic function with 1 method)

## Exemplo

In [30]:
n = 10  # dimensão de A

A = rand(n,n)

10×10 Matrix{Float64}:
 0.145377  0.625996   0.200004  0.441381  …  0.762954   0.871898   0.926526
 0.747875  0.647614   0.7704    0.09995      0.177529   0.30497    0.740285
 0.214358  0.151728   0.618867  0.732898     0.887707   0.589266   0.622149
 0.184754  0.39073    0.708894  0.113674     0.757984   0.185101   0.623418
 0.936151  0.945593   0.965829  0.406566     0.0516583  0.890145   0.472393
 0.138774  0.731243   0.377311  0.975631  …  0.390015   0.172171   0.376935
 0.855403  0.760755   0.453833  0.819575     0.490432   0.829669   0.966101
 0.422259  0.90275    0.922058  0.188242     0.684033   0.858356   0.546261
 0.335879  0.0690079  0.025054  0.598507     0.70218    0.0129325  0.905382
 0.432949  0.562359   0.833341  0.642164     0.0100311  0.196977   0.26351

In [53]:
# Ajustando os pivots de A
A = A - diagm(diag(A)) + 1.e-16*I

10×10 Matrix{Float64}:
 1.0e-16   0.625996   0.200004  0.441381  …  0.762954   0.871898  0.926526
 0.747875  1.0e-16    0.7704    0.09995      0.177529   0.30497   0.740285
 0.214358  0.151728   1.0e-16   0.732898     0.887707   0.589266  0.622149
 0.184754  0.39073    0.708894  1.0e-16      0.757984   0.185101  0.623418
 0.936151  0.945593   0.965829  0.406566     0.0516583  0.890145  0.472393
 0.138774  0.731243   0.377311  0.975631  …  0.390015   0.172171  0.376935
 0.855403  0.760755   0.453833  0.819575     0.490432   0.829669  0.966101
 0.422259  0.90275    0.922058  0.188242     1.0e-16    0.858356  0.546261
 0.335879  0.0690079  0.025054  0.598507     0.70218    1.0e-16   0.905382
 0.432949  0.562359   0.833341  0.642164     0.0100311  0.196977  1.0e-16

In [50]:
AA = copy(A);

x = ones(n,1);

b = A * x;

bb = copy(b);

sol = eligauss(AA,bb)

10×1 Matrix{Float64}:
  35.52713678800501
   4.0364104109188235
 -11.880597014925398
  -2.987917555081747
   5.946695095948842
  -5.20255863539446
   8.872778962331225
   6.137882018479038
  -1.4562899786780479
  -3.520966595593473

In [52]:
ne = norm(x-sol)
println("Erro: $ne")

Erro: 39.50884375034698
