# O método da Eliminação de Gauss

Vamos implementar o método da Eliminação de Gauss sem qualquer preocupação com estratégia de pivoteamento. Essas estratégias serão consideradas mais adiante.

In [1]:
using LinearAlgebra

Vamos considerar buscar a solução do sistema $Ax=b$. Para isso vamos implementar a função "eliminacao" que recebe $A$ e $b$ e retorna $\tilde{A}$ e $\tilde{b}$, onde $\tilde{A}$ é uma matriz triangular superior linha equivalente a $A$ e $\tilde{b}$ é linha equivalente a $b$.  

In [2]:
function eliminacao(A,b)
    n = size(b,1); 
    for k in 1 : n-1
        for i in k+1 : n
            m = A[i,k] / A[k,k];
            A[i,k] = 0.0;
            for j in k+1 : n
                A[i,j] = A[i,j] - m * A[k,j];
            end
            b[i] = b[i] - m * b[k];
        end
    end
    return(A,b)
end

eliminacao (generic function with 1 method)

A função "solucao" recebe as matrizes $\tilde{A}$ e $\tilde{b}$ da função anterior e calcular a solução do sistema por meio de uma substituição.

In [3]:
function solucao(A,b)
    n = size(b,1);
    x = zeros(n,1); 
    x[n] = b[n] / A[n,n];
    for k in n-1 : -1 : 1
        s = 0.0;
        for j in k+1 : n
            s = s + A[k,j] * x[j];
        end
        x[k] = (b[k] - s) / A[k,k];
    end
    return(x)
end
    

solucao (generic function with 1 method)

Com as funções acima, implementamos a função "eligauss" que dirigirá todo o processo de solução.

In [4]:
function eligauss(A,b)
    (A,b) = eliminacao(A,b);
    return solucao(A,b);
end

eligauss (generic function with 1 method)

## Exemplo

In [11]:
n = 100  # dimensão de A

A = rand(n,n)

100×100 Matrix{Float64}:
 0.184674   0.49903    0.292059  …  0.232328   0.822723    0.210694
 0.591504   0.189825   0.918437     0.396525   0.454776    0.300225
 0.0536021  0.371722   0.970752     0.316966   0.428585    0.0586645
 0.833523   0.576921   0.85848      0.670978   0.783465    0.250381
 0.257794   0.530519   0.838704     0.874184   0.87432     0.937912
 0.0852158  0.0126687  0.182403  …  0.253911   0.737813    0.157304
 0.413897   0.10078    0.8532       0.822948   0.973771    0.737687
 0.267098   0.182123   0.815732     0.0455595  0.787885    0.916848
 0.0402051  0.704265   0.940389     0.654378   0.00556528  0.194848
 0.325102   0.573084   0.295765     0.990705   0.588548    0.947175
 ⋮                               ⋱                         
 0.307421   0.181175   0.94512      0.171487   0.494305    0.682286
 0.648366   0.309636   0.462968     0.300165   0.583272    0.0432683
 0.128061   0.336012   0.974102     0.762408   0.057029    0.151824
 0.396787   0.624329   0.3631

In [12]:
# Ajustando os pivots de A
A = A - diagm(diag(A)) + 1.e-8*I

100×100 Matrix{Float64}:
 1.0e-8     0.49903    0.292059  …  0.232328   0.822723    0.210694
 0.591504   1.0e-8     0.918437     0.396525   0.454776    0.300225
 0.0536021  0.371722   1.0e-8       0.316966   0.428585    0.0586645
 0.833523   0.576921   0.85848      0.670978   0.783465    0.250381
 0.257794   0.530519   0.838704     0.874184   0.87432     0.937912
 0.0852158  0.0126687  0.182403  …  0.253911   0.737813    0.157304
 0.413897   0.10078    0.8532       0.822948   0.973771    0.737687
 0.267098   0.182123   0.815732     0.0455595  0.787885    0.916848
 0.0402051  0.704265   0.940389     0.654378   0.00556528  0.194848
 0.325102   0.573084   0.295765     0.990705   0.588548    0.947175
 ⋮                               ⋱                         
 0.307421   0.181175   0.94512      0.171487   0.494305    0.682286
 0.648366   0.309636   0.462968     0.300165   0.583272    0.0432683
 0.128061   0.336012   0.974102     0.762408   0.057029    0.151824
 0.396787   0.624329   0.3631

In [13]:
AA = copy(A);

x = ones(n,1);

b = A * x;

bb = copy(b);

sol = eligauss(AA,bb)

100×1 Matrix{Float64}:
 1.000000082740371
 0.9999991147370173
 1.0000029791819367
 0.999998355179713
 1.0000004216796643
 1.000000725030775
 1.0000000525529438
 0.9999978120366441
 1.0000002425936283
 0.9999982481637627
 ⋮
 0.9999977387833107
 0.9999976397144094
 0.999999866705084
 1.000004249534355
 0.99999952514705
 1.0000024775635077
 1.0000001516087536
 1.0000001200434114
 1.0000012841270294

In [14]:
ne = norm(x-sol)
println("Erro: $ne")

Erro: 2.0333203517217673e-5
